import json
import os
from collections import defaultdict

TABLE_HEADER = "YEP_USE_DISPATCH_TABLE_SECTION const FunctionDescriptor<YepStatus (YEPABI*)(%s *YEP_RESTRICT, " \
        "%s *YEP_RESTRICT, %s *YEP_RESTRICT, YepSize)> _dispatchTable_%s[] = {"
IMPLEMENTATION_DESCRIPTION = "YEP_DESCRIBE_FUNCTION_IMPLEMENTATION(%s, %s, %s, %s, %s, \"asm\", YEP_NULL_POINTER, YEP_NULL_POINTER)"
filename = "library/sources/core/Dispatch_Tables.cpp"

x86_64_SIMD_EXTENSIONS = {
    "Nehalem"       : ["YepX86SimdFeatureSSE", "YepX86SimdFeatureSSE2"],
    "SandyBridge"   : ["YepX86SimdFeatureAVX"],
    "Haswell"       : ["YepX86SimdFeatureAVX2", "YepX86SimdFeatureAVX"]
}

x86_64_SYSTEM_FEATURES = {
    ("Nehalem", "Microsoft")        : ["YepX86SystemFeatureXMM"],
    ("SandyBridge", "Microsoft")    : ["YepX86SystemFeatureYMM"],
    ("Haswell", "Microsoft")        : ["YepX86SystemFeatureYMM"],
    ("Nehalem", "SysV")             : ["YepX86SystemFeatureXMM"],
    ("SandyBridge", "SysV")         : ["YepX86SystemFeatureYMM"],
    ("Haswell", "SysV")             : ["YepX86SystemFeatureYMM"]
}

def write_table_header(func_metadata):
    """
    Writes the dispatch table header to the output file
    :param func_metadata JSON metadata generated by PeachPy during compilation
    """
    arg_type_input = filter(lambda arg: arg["name"] == "xPointer", func_metadata["arguments"])[0]["type"]
    arg_type_output = filter(lambda arg: arg["name"] == "zPointer", func_metadata["arguments"])[0]["type"]
    func_name = func_metadata["name"]
    with open(filename, "a") as f:
        f.write(TABLE_HEADER % (arg_type_input, arg_type_input, arg_type_output, func_name))
        f.write('\n')

def write_microsoft_abi(func_metadata):
    target_arch = func_metadata["uarch"]
    isa_extensions = "YepIsaFeaturesDefault"
    simd_extensions = x86_64_SIMD_EXTENSIONS[target_arch]
    system_extensions = x86_64_SYSTEM_FEATURES[(target_arch, "Microsoft")]
    yep_target_arch = "YepCpuMicroarchitecture" + target_arch
    with open(filename, "a") as f:
        f.write(IMPLEMENTATION_DESCRIPTION % (func_metadata["name"], isa_extensions, \
            ' | '.join(simd_extensions), ' | '.join(system_extensions), yep_target_arch))
        f.write('\n')

def write_systemv_abi(func_metadata):
    target_arch = func_metadata["uarch"]
    isa_extensions = "YepIsaFeaturesDefault"
    simd_extensions = x86_64_SIMD_EXTENSIONS[target_arch]
    system_extensions = x86_64_SYSTEM_FEATURES[(target_arch, "SysV")]
    yep_target_arch = "YepCpuMicroarchitecture" + target_arch
    with open(filename, "a") as f:
        f.write('    ')
        f.write(IMPLEMENTATION_DESCRIPTION % (func_metadata["name"], isa_extensions, \
                ' | '.join(simd_extensions), ' | '.join(system_extensions), yep_target_arch))
        f.write('\n')

def generate_includes(src_dir):
    with open(filename, "w") as f:
        f.write("#include <yepPrivate.h>\n")
        for dir_path,subdirs,build_files in os.walk(src_dir):
            for build_file in build_files:
                if build_file.endswith(".h"):
                    print build_file
                    f.write("#include \"%s\"\n" % build_file)

if __name__ == "__main__":
    build_dir = "library/build/x86_64-osx/core"
    generate_includes("library/sources/core")
    json_files = filter(lambda f: f.endswith(".json"), os.listdir(build_dir))
    decoder = json.JSONDecoder()
    function_dict = defaultdict(list)
    for json_file in json_files:
        metadata = decoder.decode(' '.join(open(os.path.join(build_dir, json_file), "r").readlines()))
        for func_data in metadata:
            func_name = func_data["name"]
            function_dict[func_name].append(func_data)
    for func,data_list in function_dict.items():
        write_table_header(data_list[0])
        for data in data_list:
            if data["abi"] == "ms":
                write_microsoft_abi(data)
            if data["abi"] == "SystemV x86-64 ABI":
                write_systemv_abi(data)
        with open(filename, "a") as f:
            f.write("};")
            f.write("\n")

