/*
 *                       Yeppp! library implementation
 *                   This file is auto-generated by Peach-Py,
 *        Portable Efficient Assembly Code-generator in Higher-level Python,
 *                  part of the Yeppp! library infrastructure
 * This file is part of Yeppp! library and licensed under the New BSD license.
 * See library/LICENSE.txt for the full text of the license.
 */

#include <jni.h>
#include <yepCore.h>


JNIEXPORT jfloat JNICALL Java_info_yeppp_Core_DotProduct_1V32fV32f_1S32f(JNIEnv *env, jclass class, jfloatArray xArray, jint xOffset, jfloatArray yArray, jint yOffset, jint length) {
	enum YepStatus status;
	Yep32f dotProduct;
	jfloat* xPointer = NULL;
	jfloat* yPointer = NULL;

	xPointer = (*env)->GetPrimitiveArrayCritical(env, xArray, NULL);
	yPointer = (*env)->GetPrimitiveArrayCritical(env, yArray, NULL);

	status = yepCore_DotProduct_V32fV32f_S32f(&xPointer[xOffset], &yPointer[yOffset], &dotProduct, length);

	(*env)->ReleasePrimitiveArrayCritical(env, xArray, xPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, yArray, yPointer, JNI_ABORT);

	return dotProduct;
}

JNIEXPORT jdouble JNICALL Java_info_yeppp_Core_DotProduct_1V64fV64f_1S64f(JNIEnv *env, jclass class, jdoubleArray xArray, jint xOffset, jdoubleArray yArray, jint yOffset, jint length) {
	enum YepStatus status;
	Yep64f dotProduct;
	jdouble* xPointer = NULL;
	jdouble* yPointer = NULL;

	xPointer = (*env)->GetPrimitiveArrayCritical(env, xArray, NULL);
	yPointer = (*env)->GetPrimitiveArrayCritical(env, yArray, NULL);

	status = yepCore_DotProduct_V64fV64f_S64f(&xPointer[xOffset], &yPointer[yOffset], &dotProduct, length);

	(*env)->ReleasePrimitiveArrayCritical(env, xArray, xPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, yArray, yPointer, JNI_ABORT);

	return dotProduct;
}
