/*
 *                       Yeppp! library implementation
 *                   This file is auto-generated by Peach-Py,
 *        Portable Efficient Assembly Code-generator in Higher-level Python,
 *                  part of the Yeppp! library infrastructure
 * This file is part of Yeppp! library and licensed under the New BSD license.
 * See library/LICENSE.txt for the full text of the license.
 */

#include <jni.h>
#include <yepCore.h>


JNIEXPORT void JNICALL Java_info_yeppp_Core_Subtract_1V8uV8u_1V8u(JNIEnv *env, jclass class, jbyteArray xArray, jint xOffset, jbyteArray yArray, jint yOffset, jbyteArray differenceArray, jint differenceOffset, jint length) {
	enum YepStatus status;
	jbyte* xPointer = NULL;
	jbyte* yPointer = NULL;
	jbyte* differencePointer = NULL;

	xPointer = (*env)->GetPrimitiveArrayCritical(env, xArray, NULL);
	yPointer = (*env)->GetPrimitiveArrayCritical(env, yArray, NULL);
	differencePointer = (*env)->GetPrimitiveArrayCritical(env, differenceArray, NULL);

	status = yepCore_Subtract_V8uV8u_V8u(&xPointer[xOffset], &yPointer[yOffset], &differencePointer[differenceOffset], length);

	(*env)->ReleasePrimitiveArrayCritical(env, xArray, xPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, yArray, yPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, differenceArray, differencePointer, 0);
}

JNIEXPORT void JNICALL Java_info_yeppp_Core_Subtract_1V8uV8u_1V16u(JNIEnv *env, jclass class, jbyteArray xArray, jint xOffset, jbyteArray yArray, jint yOffset, jshortArray differenceArray, jint differenceOffset, jint length) {
	enum YepStatus status;
	jbyte* xPointer = NULL;
	jbyte* yPointer = NULL;
	jshort* differencePointer = NULL;

	xPointer = (*env)->GetPrimitiveArrayCritical(env, xArray, NULL);
	yPointer = (*env)->GetPrimitiveArrayCritical(env, yArray, NULL);
	differencePointer = (*env)->GetPrimitiveArrayCritical(env, differenceArray, NULL);

	status = yepCore_Subtract_V8uV8u_V16u(&xPointer[xOffset], &yPointer[yOffset], &differencePointer[differenceOffset], length);

	(*env)->ReleasePrimitiveArrayCritical(env, xArray, xPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, yArray, yPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, differenceArray, differencePointer, 0);
}

JNIEXPORT void JNICALL Java_info_yeppp_Core_Subtract_1V8sV8s_1V16s(JNIEnv *env, jclass class, jbyteArray xArray, jint xOffset, jbyteArray yArray, jint yOffset, jshortArray differenceArray, jint differenceOffset, jint length) {
	enum YepStatus status;
	jbyte* xPointer = NULL;
	jbyte* yPointer = NULL;
	jshort* differencePointer = NULL;

	xPointer = (*env)->GetPrimitiveArrayCritical(env, xArray, NULL);
	yPointer = (*env)->GetPrimitiveArrayCritical(env, yArray, NULL);
	differencePointer = (*env)->GetPrimitiveArrayCritical(env, differenceArray, NULL);

	status = yepCore_Subtract_V8sV8s_V16s(&xPointer[xOffset], &yPointer[yOffset], &differencePointer[differenceOffset], length);

	(*env)->ReleasePrimitiveArrayCritical(env, xArray, xPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, yArray, yPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, differenceArray, differencePointer, 0);
}

JNIEXPORT void JNICALL Java_info_yeppp_Core_Subtract_1V16uV16u_1V16u(JNIEnv *env, jclass class, jshortArray xArray, jint xOffset, jshortArray yArray, jint yOffset, jshortArray differenceArray, jint differenceOffset, jint length) {
	enum YepStatus status;
	jshort* xPointer = NULL;
	jshort* yPointer = NULL;
	jshort* differencePointer = NULL;

	xPointer = (*env)->GetPrimitiveArrayCritical(env, xArray, NULL);
	yPointer = (*env)->GetPrimitiveArrayCritical(env, yArray, NULL);
	differencePointer = (*env)->GetPrimitiveArrayCritical(env, differenceArray, NULL);

	status = yepCore_Subtract_V16uV16u_V16u(&xPointer[xOffset], &yPointer[yOffset], &differencePointer[differenceOffset], length);

	(*env)->ReleasePrimitiveArrayCritical(env, xArray, xPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, yArray, yPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, differenceArray, differencePointer, 0);
}

JNIEXPORT void JNICALL Java_info_yeppp_Core_Subtract_1V16uV16u_1V32u(JNIEnv *env, jclass class, jshortArray xArray, jint xOffset, jshortArray yArray, jint yOffset, jintArray differenceArray, jint differenceOffset, jint length) {
	enum YepStatus status;
	jshort* xPointer = NULL;
	jshort* yPointer = NULL;
	jint* differencePointer = NULL;

	xPointer = (*env)->GetPrimitiveArrayCritical(env, xArray, NULL);
	yPointer = (*env)->GetPrimitiveArrayCritical(env, yArray, NULL);
	differencePointer = (*env)->GetPrimitiveArrayCritical(env, differenceArray, NULL);

	status = yepCore_Subtract_V16uV16u_V32u(&xPointer[xOffset], &yPointer[yOffset], &differencePointer[differenceOffset], length);

	(*env)->ReleasePrimitiveArrayCritical(env, xArray, xPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, yArray, yPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, differenceArray, differencePointer, 0);
}

JNIEXPORT void JNICALL Java_info_yeppp_Core_Subtract_1V16sV16s_1V32s(JNIEnv *env, jclass class, jshortArray xArray, jint xOffset, jshortArray yArray, jint yOffset, jintArray differenceArray, jint differenceOffset, jint length) {
	enum YepStatus status;
	jshort* xPointer = NULL;
	jshort* yPointer = NULL;
	jint* differencePointer = NULL;

	xPointer = (*env)->GetPrimitiveArrayCritical(env, xArray, NULL);
	yPointer = (*env)->GetPrimitiveArrayCritical(env, yArray, NULL);
	differencePointer = (*env)->GetPrimitiveArrayCritical(env, differenceArray, NULL);

	status = yepCore_Subtract_V16sV16s_V32s(&xPointer[xOffset], &yPointer[yOffset], &differencePointer[differenceOffset], length);

	(*env)->ReleasePrimitiveArrayCritical(env, xArray, xPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, yArray, yPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, differenceArray, differencePointer, 0);
}

JNIEXPORT void JNICALL Java_info_yeppp_Core_Subtract_1V32uV32u_1V32u(JNIEnv *env, jclass class, jintArray xArray, jint xOffset, jintArray yArray, jint yOffset, jintArray differenceArray, jint differenceOffset, jint length) {
	enum YepStatus status;
	jint* xPointer = NULL;
	jint* yPointer = NULL;
	jint* differencePointer = NULL;

	xPointer = (*env)->GetPrimitiveArrayCritical(env, xArray, NULL);
	yPointer = (*env)->GetPrimitiveArrayCritical(env, yArray, NULL);
	differencePointer = (*env)->GetPrimitiveArrayCritical(env, differenceArray, NULL);

	status = yepCore_Subtract_V32uV32u_V32u(&xPointer[xOffset], &yPointer[yOffset], &differencePointer[differenceOffset], length);

	(*env)->ReleasePrimitiveArrayCritical(env, xArray, xPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, yArray, yPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, differenceArray, differencePointer, 0);
}

JNIEXPORT void JNICALL Java_info_yeppp_Core_Subtract_1V32uV32u_1V64u(JNIEnv *env, jclass class, jintArray xArray, jint xOffset, jintArray yArray, jint yOffset, jlongArray differenceArray, jint differenceOffset, jint length) {
	enum YepStatus status;
	jint* xPointer = NULL;
	jint* yPointer = NULL;
	jlong* differencePointer = NULL;

	xPointer = (*env)->GetPrimitiveArrayCritical(env, xArray, NULL);
	yPointer = (*env)->GetPrimitiveArrayCritical(env, yArray, NULL);
	differencePointer = (*env)->GetPrimitiveArrayCritical(env, differenceArray, NULL);

	status = yepCore_Subtract_V32uV32u_V64u(&xPointer[xOffset], &yPointer[yOffset], &differencePointer[differenceOffset], length);

	(*env)->ReleasePrimitiveArrayCritical(env, xArray, xPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, yArray, yPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, differenceArray, differencePointer, 0);
}

JNIEXPORT void JNICALL Java_info_yeppp_Core_Subtract_1V32sV32s_1V64s(JNIEnv *env, jclass class, jintArray xArray, jint xOffset, jintArray yArray, jint yOffset, jlongArray differenceArray, jint differenceOffset, jint length) {
	enum YepStatus status;
	jint* xPointer = NULL;
	jint* yPointer = NULL;
	jlong* differencePointer = NULL;

	xPointer = (*env)->GetPrimitiveArrayCritical(env, xArray, NULL);
	yPointer = (*env)->GetPrimitiveArrayCritical(env, yArray, NULL);
	differencePointer = (*env)->GetPrimitiveArrayCritical(env, differenceArray, NULL);

	status = yepCore_Subtract_V32sV32s_V64s(&xPointer[xOffset], &yPointer[yOffset], &differencePointer[differenceOffset], length);

	(*env)->ReleasePrimitiveArrayCritical(env, xArray, xPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, yArray, yPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, differenceArray, differencePointer, 0);
}

JNIEXPORT void JNICALL Java_info_yeppp_Core_Subtract_1V64uV64u_1V64u(JNIEnv *env, jclass class, jlongArray xArray, jint xOffset, jlongArray yArray, jint yOffset, jlongArray differenceArray, jint differenceOffset, jint length) {
	enum YepStatus status;
	jlong* xPointer = NULL;
	jlong* yPointer = NULL;
	jlong* differencePointer = NULL;

	xPointer = (*env)->GetPrimitiveArrayCritical(env, xArray, NULL);
	yPointer = (*env)->GetPrimitiveArrayCritical(env, yArray, NULL);
	differencePointer = (*env)->GetPrimitiveArrayCritical(env, differenceArray, NULL);

	status = yepCore_Subtract_V64uV64u_V64u(&xPointer[xOffset], &yPointer[yOffset], &differencePointer[differenceOffset], length);

	(*env)->ReleasePrimitiveArrayCritical(env, xArray, xPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, yArray, yPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, differenceArray, differencePointer, 0);
}

JNIEXPORT void JNICALL Java_info_yeppp_Core_Subtract_1V32fV32f_1V32f(JNIEnv *env, jclass class, jfloatArray xArray, jint xOffset, jfloatArray yArray, jint yOffset, jfloatArray differenceArray, jint differenceOffset, jint length) {
	enum YepStatus status;
	jfloat* xPointer = NULL;
	jfloat* yPointer = NULL;
	jfloat* differencePointer = NULL;

	xPointer = (*env)->GetPrimitiveArrayCritical(env, xArray, NULL);
	yPointer = (*env)->GetPrimitiveArrayCritical(env, yArray, NULL);
	differencePointer = (*env)->GetPrimitiveArrayCritical(env, differenceArray, NULL);

	status = yepCore_Subtract_V32fV32f_V32f(&xPointer[xOffset], &yPointer[yOffset], &differencePointer[differenceOffset], length);

	(*env)->ReleasePrimitiveArrayCritical(env, xArray, xPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, yArray, yPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, differenceArray, differencePointer, 0);
}

JNIEXPORT void JNICALL Java_info_yeppp_Core_Subtract_1V64fV64f_1V64f(JNIEnv *env, jclass class, jdoubleArray xArray, jint xOffset, jdoubleArray yArray, jint yOffset, jdoubleArray differenceArray, jint differenceOffset, jint length) {
	enum YepStatus status;
	jdouble* xPointer = NULL;
	jdouble* yPointer = NULL;
	jdouble* differencePointer = NULL;

	xPointer = (*env)->GetPrimitiveArrayCritical(env, xArray, NULL);
	yPointer = (*env)->GetPrimitiveArrayCritical(env, yArray, NULL);
	differencePointer = (*env)->GetPrimitiveArrayCritical(env, differenceArray, NULL);

	status = yepCore_Subtract_V64fV64f_V64f(&xPointer[xOffset], &yPointer[yOffset], &differencePointer[differenceOffset], length);

	(*env)->ReleasePrimitiveArrayCritical(env, xArray, xPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, yArray, yPointer, JNI_ABORT);
	(*env)->ReleasePrimitiveArrayCritical(env, differenceArray, differencePointer, 0);
}
