/*
 *                       Yeppp! library implementation
 *                   This file is auto-generated by Peach-Py,
 *        Portable Efficient Assembly Code-generator in Higher-level Python,
 *                  part of the Yeppp! library infrastructure
 * This file is part of Yeppp! library and licensed under the New BSD license.
 * See library/LICENSE.txt for the full text of the license.
 */

#include <jni.h>
#include <yepCore.h>


JNIEXPORT jfloat JNICALL Java_info_yeppp_Core_SumSquares_1V32f_1S32f(JNIEnv *env, jclass class, jfloatArray numberArray, jint numberOffset, jint length) {
	enum YepStatus status;
	Yep32f sumSquares;
	jfloat* numberPointer = NULL;

	numberPointer = (*env)->GetPrimitiveArrayCritical(env, numberArray, NULL);

	status = yepCore_SumSquares_V32f_S32f(&numberPointer[numberOffset], &sumSquares, length);

	(*env)->ReleasePrimitiveArrayCritical(env, numberArray, numberPointer, JNI_ABORT);

	return sumSquares;
}

JNIEXPORT jdouble JNICALL Java_info_yeppp_Core_SumSquares_1V64f_1S64f(JNIEnv *env, jclass class, jdoubleArray numberArray, jint numberOffset, jint length) {
	enum YepStatus status;
	Yep64f sumSquares;
	jdouble* numberPointer = NULL;

	numberPointer = (*env)->GetPrimitiveArrayCritical(env, numberArray, NULL);

	status = yepCore_SumSquares_V64f_S64f(&numberPointer[numberOffset], &sumSquares, length);

	(*env)->ReleasePrimitiveArrayCritical(env, numberArray, numberPointer, JNI_ABORT);

	return sumSquares;
}
